#!/bin/bash
user=devops
mydir=~/test

if [ -d  $mydir ];
then
  echo "The folder exists."
else
  echo "The folder does not exists."
fi

if grep $user /etc/passwd
then
sudo chown -R $user:$user $mydir
echo "The user $user is owner of $mydir"
else
echo "The user $user doesn’t exist"
fi
